name: demo
on: 
  push:
    branches:
      - main

jobs:
  updateFiles:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
      
      - name: extract git commit data
        uses: rleaspinasse/git-commit-data-action@v1.x
      
      - name: Update author information
        run: echo  ${{env.GIT_COMMIT_AUTHOR_NAME}} > AUTHOR
        
      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: main
          title: "demo for auto pr"
          committer: ${{env}} ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is a PR to show automatic PR creation 
          token: ${{ secrets.GITHUB_TOKEN}}
          delete-branch: true
        

        

  
        
