name: demo
on: 
  push:
    branches:
      - main
    paths:
      - tag_file
  workflow_call:
  workflow_dispatch:

jobs:
  updateFiles:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: change readme
        run: |
          new_tag=`cat tag_file`
          old_tag=`cat old_tag`
          echo $new_tag
          echo $old_tag
          sed -i "s/$old_tag/$new_tag/g" README.md
          cat README.md
          git config --global user.name "karki1s"
          git config --global user.email "sk.karkisuman@gmail.com"
          git add .
          git commit -m 'changed readme'
          git push -u origin main
          
      

        

  
        
