name: demo
on: 
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  updateFiles:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
        
      - name: auto commit 
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: Self
          author_email: self@example.com
          commit: --signoff
          message: 'Updated read me tag changed'
          push: true
          
      - name: change readme
        run: |
          new_tag=`cat tag_file`
          old_tag=`cat old_tag`
          sed "s/$old_tag/$new_tag/" README.md

        

  
        
